package com.example.demo;

import java.io.Serializable;
import java.util.ArrayList;

public class Cours implements Serializable {
    // Generated by VSCODE
    private static final long serialVersionUID = 5257120107096513127L;

    private int id;
    private String libelle;
    private ArrayList<Objectif> mesObjectifs = new ArrayList<Objectif>();

    Cours() {

    }

    Cours(int myID, String myLibelle) {
        this.id = myID;
        this.libelle = myLibelle;
    }
    public int getId(){
        return this.id;
    }
    public String getLibelle(){
        return this.libelle;
    }

    public ArrayList<Objectif> getObjectifs(){
        return this.mesObjectifs;
    }

    public String objToString(ArrayList<Objectif> _Objectif){
        String lesObjs = "";
        for (int i = 0; i < _Objectif.size(); i++) {
            lesObjs += _Objectif.get(i).getLibelle() + "; ";
        }
        return lesObjs;
    }

    public void setLibelle(String newLibelle){
        this.libelle = newLibelle;
    }
    public void setId(int newId){
        this.id = newId;
    }
    public void addObjectif(Objectif newObj) {
        this.mesObjectifs.add(newObj);
    }

    public void afficher() {
        System.out.println("ID du cours : " + this.id + ", Libelle : " + this.libelle + ", a pour objectifs : " + objToString(this.mesObjectifs));
    }
}


// Vous allez donc faire un clic sur le projet New > Java Class dont le nom sera Cours.java
// Un cours possède comme attribut, un int qui s'appelera id et sera l'identifiant du cours, ainsi qu'une String pour le libellé.
// Il nous faudra respecter pour cette classe, le modèle d'un bean. 
// Les conventions à respecter sont les suivantes : 
// •	la classe doit être « Serializable » pour pouvoir sauvegarder et restaurer l'état d'instances de cette classe ;
// •	la classe doit posséder un constructeur sans paramètre (constructeur par défaut) ;
// •	les attributs privés de la classe (variables d'instances) doivent être accessibles publiquement via des méthodes accesseurs construit avec get ou set suivi du nom de l'attribut avec la première lettre capitalisée. Le couple d’accesseurs est appelé Propriété ;
// •	la classe ne doit pas être déclarée final.

// Vous créerez ainsi cette classe Cours en respectant toutes ces conventions et ajouter également une méthode void afficher() qui affiche une représentation d'un objet Cours.
//  Placez ensuite cette classe dans le package com.esgi;
