package com.example.demo;

import java.io.Serializable;

public class Objectif implements Serializable {
     // Generated by VSCODE
     private static final long serialVersionUID = 5257120107096513127L;

     private int id;
     private String libelle;
 
     Objectif() {
 
     }
 
     Objectif(int myID, String myLibelle) {
         this.id = myID;
         this.libelle = myLibelle;
     }
     public int getId(){
         return this.id;
     }
     public String getLibelle(){
         return this.libelle;
     }
 
     public void setLibelle(String newLibelle){
         this.libelle = newLibelle;
     }
     public void setId(int newId){
         this.id = newId;
     }
 
     public void afficher() {
         System.out.println("Object ID : " + this.id + ", Libelle : " + this.libelle);
     }
}
